name: My Badges

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * Sun'

jobs:
  my-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Update My Badges
        uses: my-badges/my-badges@master
        with:
          compact: true    
