name: My Badges

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  my-badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: my-badges/my-badges@master
      #   with:
      #     dryrun: true
      # - name: Update My Badges
      #   run: npx update-my-badges ${{github.repository_owner}}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: sed -i '/<h4>.*My Badges/d' README.md
      - run: |
          git fetch -1
          git pull
          git rev-parse HEAD
          git add README.md
          if [ "$(git diff --cached)" ]
          then
            git -c user.name='github-actions[bot]' \
                -c user.email='41898282+github-actions[bot]@users.noreply.github.com' \
              commit 
            git push --force-with-lease origin
          fi
           
