name: My Starlines

on:
  schedule:
    - cron: '0 0 * * 0'  # weekly
  push:
    paths:
      - .github/workflows/starlines.yml
  workflow_dispatch:

jobs:
  starline:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - uses: qoomon/starlines@main
        with: 
         resource: qoomon
         github-token: ${{ secrets.ACCESS_TOKEN }}
          
      - uses: qoomon/starlines@main
        with:
          resource: qoomon/5dfcdf8eec66a051ecd85625518cfd13@gist
          github-token: ${{ secrets.ACCESS_TOKEN }}

      - uses: qoomon/actions--setup-git@v1
      - run: |
          git pull --rebase --autostash
          git add starlines
          git commit -m "chore: update starlines" || true
          git push 
